/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CustomerRouteImport } from './routes/customer'
import { Route as GuestRouteImport } from './routes/guest'
import { Route as HubRouteImport } from './routes/hub'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as TrainerRouteImport } from './routes/trainer'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as PublicForgotPasswordRouteImport } from './routes/_public.forgot-password'
import { Route as PublicGymInfoRouteImport } from './routes/_public.gym-info'
import { Route as PublicLoginRouteImport } from './routes/_public.login'
import { Route as PublicRegisterRouteImport } from './routes/_public.register'
import { Route as PublicRegisterTrainerRouteImport } from './routes/_public.register-trainer'
import { Route as PublicReviewsRouteImport } from './routes/_public.reviews'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminBranchesRouteImport } from './routes/admin.branches'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as CustomerIndexRouteImport } from './routes/customer.index'
import { Route as CustomerAssessmentRouteImport } from './routes/customer.assessment'
import { Route as CustomerAvailabilityRouteImport } from './routes/customer.availability'
import { Route as CustomerBookPtRouteImport } from './routes/customer.book-pt'
import { Route as CustomerChangePasswordRouteImport } from './routes/customer.change-password'
import { Route as CustomerCheckInRouteImport } from './routes/customer.check-in'
import { Route as CustomerCheckInScreenRouteImport } from './routes/customer.check-in-screen'
import { Route as CustomerMetricsRouteImport } from './routes/customer.metrics'
import { Route as CustomerPackagesRouteImport } from './routes/customer.packages'
import { Route as CustomerProfileRouteImport } from './routes/customer.profile'
import { Route as CustomerPurchaseRouteImport } from './routes/customer.purchase'
import { Route as CustomerRefundRouteImport } from './routes/customer.refund'
import { Route as CustomerRescheduleRouteImport } from './routes/customer.reschedule'
import { Route as CustomerReviewRouteImport } from './routes/customer.review'
import { Route as CustomerScheduleRouteImport } from './routes/customer.schedule'
import { Route as ManagerIndexRouteImport } from './routes/manager.index'
import { Route as ManagerMembershipsRouteImport } from './routes/manager.memberships'
import { Route as ManagerReportsRouteImport } from './routes/manager.reports'
import { Route as ManagerStaffRouteImport } from './routes/manager.staff'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as StaffCheckInRouteImport } from './routes/staff.check-in'
import { Route as StaffClassesRouteImport } from './routes/staff.classes'
import { Route as StaffMembersRouteImport } from './routes/staff.members'
import { Route as TrainerIndexRouteImport } from './routes/trainer.index'
import { Route as TrainerClientsRouteImport } from './routes/trainer.clients'
import { Route as TrainerProgramsRouteImport } from './routes/trainer.programs'
import { Route as TrainerScheduleRouteImport } from './routes/trainer.schedule'
import { Route as PublicArticlesIndexRouteImport } from './routes/_public.articles.index'
import { Route as PublicArticlesIdRouteImport } from './routes/_public.articles.$id'
import { Route as PublicPackagesIndexRouteImport } from './routes/_public.packages.index'
import { Route as PublicPackagesIdRouteImport } from './routes/_public.packages.$id'
import { Route as PublicToolsFitnessCalculatorRouteImport } from './routes/_public.tools.fitness-calculator'
import { Route as PublicTrainersIndexRouteImport } from './routes/_public.trainers.index'
import { Route as PublicTrainersIdRouteImport } from './routes/_public.trainers.$id'
import { Route as CustomerSessionsIndexRouteImport } from './routes/customer.sessions.index'
import { Route as CustomerSessionsIdRouteImport } from './routes/customer.sessions.$id'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoute = CustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/guest',
  path: '/guest',
  getParentRoute: () => rootRouteImport,
} as any)
const HubRoute = HubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerRoute = TrainerRouteImport.update({
  id: '/trainer',
  path: '/trainer',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicForgotPasswordRoute = PublicForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => PublicRoute,
} as any)
const PublicGymInfoRoute = PublicGymInfoRouteImport.update({
  id: '/gym-info',
  path: '/gym-info',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicRoute,
} as any)
const PublicRegisterTrainerRoute = PublicRegisterTrainerRouteImport.update({
  id: '/register-trainer',
  path: '/register-trainer',
  getParentRoute: () => PublicRoute,
} as any)
const PublicReviewsRoute = PublicReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => PublicRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBranchesRoute = AdminBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const CustomerIndexRoute = CustomerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerAssessmentRoute = CustomerAssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerAvailabilityRoute = CustomerAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerBookPtRoute = CustomerBookPtRouteImport.update({
  id: '/book-pt',
  path: '/book-pt',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerChangePasswordRoute = CustomerChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerCheckInRoute = CustomerCheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerCheckInScreenRoute = CustomerCheckInScreenRouteImport.update({
  id: '/check-in-screen',
  path: '/check-in-screen',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerMetricsRoute = CustomerMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerPackagesRoute = CustomerPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerProfileRoute = CustomerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerPurchaseRoute = CustomerPurchaseRouteImport.update({
  id: '/purchase',
  path: '/purchase',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerRefundRoute = CustomerRefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerRescheduleRoute = CustomerRescheduleRouteImport.update({
  id: '/reschedule',
  path: '/reschedule',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerReviewRoute = CustomerReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerScheduleRoute = CustomerScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => CustomerRoute,
} as any)
const ManagerIndexRoute = ManagerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerMembershipsRoute = ManagerMembershipsRouteImport.update({
  id: '/memberships',
  path: '/memberships',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerReportsRoute = ManagerReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerStaffRoute = ManagerStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => ManagerRoute,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const StaffCheckInRoute = StaffCheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => StaffRoute,
} as any)
const StaffClassesRoute = StaffClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => StaffRoute,
} as any)
const StaffMembersRoute = StaffMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => StaffRoute,
} as any)
const TrainerIndexRoute = TrainerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TrainerRoute,
} as any)
const TrainerClientsRoute = TrainerClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => TrainerRoute,
} as any)
const TrainerProgramsRoute = TrainerProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => TrainerRoute,
} as any)
const TrainerScheduleRoute = TrainerScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => TrainerRoute,
} as any)
const PublicArticlesIndexRoute = PublicArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicArticlesIdRoute = PublicArticlesIdRouteImport.update({
  id: '/articles/$id',
  path: '/articles/$id',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPackagesIndexRoute = PublicPackagesIndexRouteImport.update({
  id: '/packages/',
  path: '/packages/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPackagesIdRoute = PublicPackagesIdRouteImport.update({
  id: '/packages/$id',
  path: '/packages/$id',
  getParentRoute: () => PublicRoute,
} as any)
const PublicToolsFitnessCalculatorRoute =
  PublicToolsFitnessCalculatorRouteImport.update({
    id: '/tools/fitness-calculator',
    path: '/tools/fitness-calculator',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicTrainersIndexRoute = PublicTrainersIndexRouteImport.update({
  id: '/trainers/',
  path: '/trainers/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTrainersIdRoute = PublicTrainersIdRouteImport.update({
  id: '/trainers/$id',
  path: '/trainers/$id',
  getParentRoute: () => PublicRoute,
} as any)
const CustomerSessionsIndexRoute = CustomerSessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerSessionsIdRoute = CustomerSessionsIdRouteImport.update({
  id: '/sessions/$id',
  path: '/sessions/$id',
  getParentRoute: () => CustomerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/customer': typeof CustomerRouteWithChildren
  '/guest': typeof GuestRoute
  '/hub': typeof HubRoute
  '/manager': typeof ManagerRouteWithChildren
  '/staff': typeof StaffRouteWithChildren
  '/trainer': typeof TrainerRouteWithChildren
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/gym-info': typeof PublicGymInfoRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/register-trainer': typeof PublicRegisterTrainerRoute
  '/reviews': typeof PublicReviewsRoute
  '/admin/branches': typeof AdminBranchesRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/customer/assessment': typeof CustomerAssessmentRoute
  '/customer/availability': typeof CustomerAvailabilityRoute
  '/customer/book-pt': typeof CustomerBookPtRoute
  '/customer/change-password': typeof CustomerChangePasswordRoute
  '/customer/check-in': typeof CustomerCheckInRoute
  '/customer/check-in-screen': typeof CustomerCheckInScreenRoute
  '/customer/metrics': typeof CustomerMetricsRoute
  '/customer/packages': typeof CustomerPackagesRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/customer/purchase': typeof CustomerPurchaseRoute
  '/customer/refund': typeof CustomerRefundRoute
  '/customer/reschedule': typeof CustomerRescheduleRoute
  '/customer/review': typeof CustomerReviewRoute
  '/customer/schedule': typeof CustomerScheduleRoute
  '/manager/memberships': typeof ManagerMembershipsRoute
  '/manager/reports': typeof ManagerReportsRoute
  '/manager/staff': typeof ManagerStaffRoute
  '/staff/check-in': typeof StaffCheckInRoute
  '/staff/classes': typeof StaffClassesRoute
  '/staff/members': typeof StaffMembersRoute
  '/trainer/clients': typeof TrainerClientsRoute
  '/trainer/programs': typeof TrainerProgramsRoute
  '/trainer/schedule': typeof TrainerScheduleRoute
  '/admin/': typeof AdminIndexRoute
  '/customer/': typeof CustomerIndexRoute
  '/manager/': typeof ManagerIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/trainer/': typeof TrainerIndexRoute
  '/articles/$id': typeof PublicArticlesIdRoute
  '/packages/$id': typeof PublicPackagesIdRoute
  '/tools/fitness-calculator': typeof PublicToolsFitnessCalculatorRoute
  '/trainers/$id': typeof PublicTrainersIdRoute
  '/customer/sessions/$id': typeof CustomerSessionsIdRoute
  '/articles/': typeof PublicArticlesIndexRoute
  '/packages/': typeof PublicPackagesIndexRoute
  '/trainers/': typeof PublicTrainersIndexRoute
  '/customer/sessions/': typeof CustomerSessionsIndexRoute
}
export interface FileRoutesByTo {
  '/guest': typeof GuestRoute
  '/hub': typeof HubRoute
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/gym-info': typeof PublicGymInfoRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/register-trainer': typeof PublicRegisterTrainerRoute
  '/reviews': typeof PublicReviewsRoute
  '/admin/branches': typeof AdminBranchesRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/customer/assessment': typeof CustomerAssessmentRoute
  '/customer/availability': typeof CustomerAvailabilityRoute
  '/customer/book-pt': typeof CustomerBookPtRoute
  '/customer/change-password': typeof CustomerChangePasswordRoute
  '/customer/check-in': typeof CustomerCheckInRoute
  '/customer/check-in-screen': typeof CustomerCheckInScreenRoute
  '/customer/metrics': typeof CustomerMetricsRoute
  '/customer/packages': typeof CustomerPackagesRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/customer/purchase': typeof CustomerPurchaseRoute
  '/customer/refund': typeof CustomerRefundRoute
  '/customer/reschedule': typeof CustomerRescheduleRoute
  '/customer/review': typeof CustomerReviewRoute
  '/customer/schedule': typeof CustomerScheduleRoute
  '/manager/memberships': typeof ManagerMembershipsRoute
  '/manager/reports': typeof ManagerReportsRoute
  '/manager/staff': typeof ManagerStaffRoute
  '/staff/check-in': typeof StaffCheckInRoute
  '/staff/classes': typeof StaffClassesRoute
  '/staff/members': typeof StaffMembersRoute
  '/trainer/clients': typeof TrainerClientsRoute
  '/trainer/programs': typeof TrainerProgramsRoute
  '/trainer/schedule': typeof TrainerScheduleRoute
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/customer': typeof CustomerIndexRoute
  '/manager': typeof ManagerIndexRoute
  '/staff': typeof StaffIndexRoute
  '/trainer': typeof TrainerIndexRoute
  '/articles/$id': typeof PublicArticlesIdRoute
  '/packages/$id': typeof PublicPackagesIdRoute
  '/tools/fitness-calculator': typeof PublicToolsFitnessCalculatorRoute
  '/trainers/$id': typeof PublicTrainersIdRoute
  '/customer/sessions/$id': typeof CustomerSessionsIdRoute
  '/articles': typeof PublicArticlesIndexRoute
  '/packages': typeof PublicPackagesIndexRoute
  '/trainers': typeof PublicTrainersIndexRoute
  '/customer/sessions': typeof CustomerSessionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/customer': typeof CustomerRouteWithChildren
  '/guest': typeof GuestRoute
  '/hub': typeof HubRoute
  '/manager': typeof ManagerRouteWithChildren
  '/staff': typeof StaffRouteWithChildren
  '/trainer': typeof TrainerRouteWithChildren
  '/_public/forgot-password': typeof PublicForgotPasswordRoute
  '/_public/gym-info': typeof PublicGymInfoRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/register': typeof PublicRegisterRoute
  '/_public/register-trainer': typeof PublicRegisterTrainerRoute
  '/_public/reviews': typeof PublicReviewsRoute
  '/admin/branches': typeof AdminBranchesRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/customer/assessment': typeof CustomerAssessmentRoute
  '/customer/availability': typeof CustomerAvailabilityRoute
  '/customer/book-pt': typeof CustomerBookPtRoute
  '/customer/change-password': typeof CustomerChangePasswordRoute
  '/customer/check-in': typeof CustomerCheckInRoute
  '/customer/check-in-screen': typeof CustomerCheckInScreenRoute
  '/customer/metrics': typeof CustomerMetricsRoute
  '/customer/packages': typeof CustomerPackagesRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/customer/purchase': typeof CustomerPurchaseRoute
  '/customer/refund': typeof CustomerRefundRoute
  '/customer/reschedule': typeof CustomerRescheduleRoute
  '/customer/review': typeof CustomerReviewRoute
  '/customer/schedule': typeof CustomerScheduleRoute
  '/manager/memberships': typeof ManagerMembershipsRoute
  '/manager/reports': typeof ManagerReportsRoute
  '/manager/staff': typeof ManagerStaffRoute
  '/staff/check-in': typeof StaffCheckInRoute
  '/staff/classes': typeof StaffClassesRoute
  '/staff/members': typeof StaffMembersRoute
  '/trainer/clients': typeof TrainerClientsRoute
  '/trainer/programs': typeof TrainerProgramsRoute
  '/trainer/schedule': typeof TrainerScheduleRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/customer/': typeof CustomerIndexRoute
  '/manager/': typeof ManagerIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/trainer/': typeof TrainerIndexRoute
  '/_public/articles/$id': typeof PublicArticlesIdRoute
  '/_public/packages/$id': typeof PublicPackagesIdRoute
  '/_public/tools/fitness-calculator': typeof PublicToolsFitnessCalculatorRoute
  '/_public/trainers/$id': typeof PublicTrainersIdRoute
  '/customer/sessions/$id': typeof CustomerSessionsIdRoute
  '/_public/articles/': typeof PublicArticlesIndexRoute
  '/_public/packages/': typeof PublicPackagesIndexRoute
  '/_public/trainers/': typeof PublicTrainersIndexRoute
  '/customer/sessions/': typeof CustomerSessionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/customer'
    | '/guest'
    | '/hub'
    | '/manager'
    | '/staff'
    | '/trainer'
    | '/forgot-password'
    | '/gym-info'
    | '/login'
    | '/register'
    | '/register-trainer'
    | '/reviews'
    | '/admin/branches'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/users'
    | '/customer/assessment'
    | '/customer/availability'
    | '/customer/book-pt'
    | '/customer/change-password'
    | '/customer/check-in'
    | '/customer/check-in-screen'
    | '/customer/metrics'
    | '/customer/packages'
    | '/customer/profile'
    | '/customer/purchase'
    | '/customer/refund'
    | '/customer/reschedule'
    | '/customer/review'
    | '/customer/schedule'
    | '/manager/memberships'
    | '/manager/reports'
    | '/manager/staff'
    | '/staff/check-in'
    | '/staff/classes'
    | '/staff/members'
    | '/trainer/clients'
    | '/trainer/programs'
    | '/trainer/schedule'
    | '/admin/'
    | '/customer/'
    | '/manager/'
    | '/staff/'
    | '/trainer/'
    | '/articles/$id'
    | '/packages/$id'
    | '/tools/fitness-calculator'
    | '/trainers/$id'
    | '/customer/sessions/$id'
    | '/articles/'
    | '/packages/'
    | '/trainers/'
    | '/customer/sessions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/guest'
    | '/hub'
    | '/forgot-password'
    | '/gym-info'
    | '/login'
    | '/register'
    | '/register-trainer'
    | '/reviews'
    | '/admin/branches'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/users'
    | '/customer/assessment'
    | '/customer/availability'
    | '/customer/book-pt'
    | '/customer/change-password'
    | '/customer/check-in'
    | '/customer/check-in-screen'
    | '/customer/metrics'
    | '/customer/packages'
    | '/customer/profile'
    | '/customer/purchase'
    | '/customer/refund'
    | '/customer/reschedule'
    | '/customer/review'
    | '/customer/schedule'
    | '/manager/memberships'
    | '/manager/reports'
    | '/manager/staff'
    | '/staff/check-in'
    | '/staff/classes'
    | '/staff/members'
    | '/trainer/clients'
    | '/trainer/programs'
    | '/trainer/schedule'
    | '/'
    | '/admin'
    | '/customer'
    | '/manager'
    | '/staff'
    | '/trainer'
    | '/articles/$id'
    | '/packages/$id'
    | '/tools/fitness-calculator'
    | '/trainers/$id'
    | '/customer/sessions/$id'
    | '/articles'
    | '/packages'
    | '/trainers'
    | '/customer/sessions'
  id:
    | '__root__'
    | '/_public'
    | '/admin'
    | '/customer'
    | '/guest'
    | '/hub'
    | '/manager'
    | '/staff'
    | '/trainer'
    | '/_public/forgot-password'
    | '/_public/gym-info'
    | '/_public/login'
    | '/_public/register'
    | '/_public/register-trainer'
    | '/_public/reviews'
    | '/admin/branches'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/users'
    | '/customer/assessment'
    | '/customer/availability'
    | '/customer/book-pt'
    | '/customer/change-password'
    | '/customer/check-in'
    | '/customer/check-in-screen'
    | '/customer/metrics'
    | '/customer/packages'
    | '/customer/profile'
    | '/customer/purchase'
    | '/customer/refund'
    | '/customer/reschedule'
    | '/customer/review'
    | '/customer/schedule'
    | '/manager/memberships'
    | '/manager/reports'
    | '/manager/staff'
    | '/staff/check-in'
    | '/staff/classes'
    | '/staff/members'
    | '/trainer/clients'
    | '/trainer/programs'
    | '/trainer/schedule'
    | '/_public/'
    | '/admin/'
    | '/customer/'
    | '/manager/'
    | '/staff/'
    | '/trainer/'
    | '/_public/articles/$id'
    | '/_public/packages/$id'
    | '/_public/tools/fitness-calculator'
    | '/_public/trainers/$id'
    | '/customer/sessions/$id'
    | '/_public/articles/'
    | '/_public/packages/'
    | '/_public/trainers/'
    | '/customer/sessions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  CustomerRoute: typeof CustomerRouteWithChildren
  GuestRoute: typeof GuestRoute
  HubRoute: typeof HubRoute
  ManagerRoute: typeof ManagerRouteWithChildren
  StaffRoute: typeof StaffRouteWithChildren
  TrainerRoute: typeof TrainerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest': {
      id: '/guest'
      path: '/guest'
      fullPath: '/guest'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub': {
      id: '/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof HubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer': {
      id: '/trainer'
      path: '/trainer'
      fullPath: '/trainer'
      preLoaderRoute: typeof TrainerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/forgot-password': {
      id: '/_public/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof PublicForgotPasswordRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/gym-info': {
      id: '/_public/gym-info'
      path: '/gym-info'
      fullPath: '/gym-info'
      preLoaderRoute: typeof PublicGymInfoRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/register-trainer': {
      id: '/_public/register-trainer'
      path: '/register-trainer'
      fullPath: '/register-trainer'
      preLoaderRoute: typeof PublicRegisterTrainerRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/reviews': {
      id: '/_public/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof PublicReviewsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/branches': {
      id: '/admin/branches'
      path: '/branches'
      fullPath: '/admin/branches'
      preLoaderRoute: typeof AdminBranchesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/customer/': {
      id: '/customer/'
      path: '/'
      fullPath: '/customer/'
      preLoaderRoute: typeof CustomerIndexRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/assessment': {
      id: '/customer/assessment'
      path: '/assessment'
      fullPath: '/customer/assessment'
      preLoaderRoute: typeof CustomerAssessmentRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/availability': {
      id: '/customer/availability'
      path: '/availability'
      fullPath: '/customer/availability'
      preLoaderRoute: typeof CustomerAvailabilityRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/book-pt': {
      id: '/customer/book-pt'
      path: '/book-pt'
      fullPath: '/customer/book-pt'
      preLoaderRoute: typeof CustomerBookPtRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/change-password': {
      id: '/customer/change-password'
      path: '/change-password'
      fullPath: '/customer/change-password'
      preLoaderRoute: typeof CustomerChangePasswordRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/check-in': {
      id: '/customer/check-in'
      path: '/check-in'
      fullPath: '/customer/check-in'
      preLoaderRoute: typeof CustomerCheckInRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/check-in-screen': {
      id: '/customer/check-in-screen'
      path: '/check-in-screen'
      fullPath: '/customer/check-in-screen'
      preLoaderRoute: typeof CustomerCheckInScreenRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/metrics': {
      id: '/customer/metrics'
      path: '/metrics'
      fullPath: '/customer/metrics'
      preLoaderRoute: typeof CustomerMetricsRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/packages': {
      id: '/customer/packages'
      path: '/packages'
      fullPath: '/customer/packages'
      preLoaderRoute: typeof CustomerPackagesRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/profile': {
      id: '/customer/profile'
      path: '/profile'
      fullPath: '/customer/profile'
      preLoaderRoute: typeof CustomerProfileRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/purchase': {
      id: '/customer/purchase'
      path: '/purchase'
      fullPath: '/customer/purchase'
      preLoaderRoute: typeof CustomerPurchaseRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/refund': {
      id: '/customer/refund'
      path: '/refund'
      fullPath: '/customer/refund'
      preLoaderRoute: typeof CustomerRefundRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/reschedule': {
      id: '/customer/reschedule'
      path: '/reschedule'
      fullPath: '/customer/reschedule'
      preLoaderRoute: typeof CustomerRescheduleRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/review': {
      id: '/customer/review'
      path: '/review'
      fullPath: '/customer/review'
      preLoaderRoute: typeof CustomerReviewRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/schedule': {
      id: '/customer/schedule'
      path: '/schedule'
      fullPath: '/customer/schedule'
      preLoaderRoute: typeof CustomerScheduleRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/manager/': {
      id: '/manager/'
      path: '/'
      fullPath: '/manager/'
      preLoaderRoute: typeof ManagerIndexRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/memberships': {
      id: '/manager/memberships'
      path: '/memberships'
      fullPath: '/manager/memberships'
      preLoaderRoute: typeof ManagerMembershipsRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/reports': {
      id: '/manager/reports'
      path: '/reports'
      fullPath: '/manager/reports'
      preLoaderRoute: typeof ManagerReportsRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/staff': {
      id: '/manager/staff'
      path: '/staff'
      fullPath: '/manager/staff'
      preLoaderRoute: typeof ManagerStaffRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/check-in': {
      id: '/staff/check-in'
      path: '/check-in'
      fullPath: '/staff/check-in'
      preLoaderRoute: typeof StaffCheckInRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/classes': {
      id: '/staff/classes'
      path: '/classes'
      fullPath: '/staff/classes'
      preLoaderRoute: typeof StaffClassesRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/members': {
      id: '/staff/members'
      path: '/members'
      fullPath: '/staff/members'
      preLoaderRoute: typeof StaffMembersRouteImport
      parentRoute: typeof StaffRoute
    }
    '/trainer/': {
      id: '/trainer/'
      path: '/'
      fullPath: '/trainer/'
      preLoaderRoute: typeof TrainerIndexRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/trainer/clients': {
      id: '/trainer/clients'
      path: '/clients'
      fullPath: '/trainer/clients'
      preLoaderRoute: typeof TrainerClientsRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/trainer/programs': {
      id: '/trainer/programs'
      path: '/programs'
      fullPath: '/trainer/programs'
      preLoaderRoute: typeof TrainerProgramsRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/trainer/schedule': {
      id: '/trainer/schedule'
      path: '/schedule'
      fullPath: '/trainer/schedule'
      preLoaderRoute: typeof TrainerScheduleRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/_public/articles/': {
      id: '/_public/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof PublicArticlesIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/articles/$id': {
      id: '/_public/articles/$id'
      path: '/articles/$id'
      fullPath: '/articles/$id'
      preLoaderRoute: typeof PublicArticlesIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/packages/': {
      id: '/_public/packages/'
      path: '/packages'
      fullPath: '/packages/'
      preLoaderRoute: typeof PublicPackagesIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/packages/$id': {
      id: '/_public/packages/$id'
      path: '/packages/$id'
      fullPath: '/packages/$id'
      preLoaderRoute: typeof PublicPackagesIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/tools/fitness-calculator': {
      id: '/_public/tools/fitness-calculator'
      path: '/tools/fitness-calculator'
      fullPath: '/tools/fitness-calculator'
      preLoaderRoute: typeof PublicToolsFitnessCalculatorRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/trainers/': {
      id: '/_public/trainers/'
      path: '/trainers'
      fullPath: '/trainers/'
      preLoaderRoute: typeof PublicTrainersIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/trainers/$id': {
      id: '/_public/trainers/$id'
      path: '/trainers/$id'
      fullPath: '/trainers/$id'
      preLoaderRoute: typeof PublicTrainersIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/customer/sessions/': {
      id: '/customer/sessions/'
      path: '/sessions'
      fullPath: '/customer/sessions/'
      preLoaderRoute: typeof CustomerSessionsIndexRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/sessions/$id': {
      id: '/customer/sessions/$id'
      path: '/sessions/$id'
      fullPath: '/customer/sessions/$id'
      preLoaderRoute: typeof CustomerSessionsIdRouteImport
      parentRoute: typeof CustomerRoute
    }
  }
}

interface PublicRouteChildren {
  PublicForgotPasswordRoute: typeof PublicForgotPasswordRoute
  PublicGymInfoRoute: typeof PublicGymInfoRoute
  PublicLoginRoute: typeof PublicLoginRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
  PublicRegisterTrainerRoute: typeof PublicRegisterTrainerRoute
  PublicReviewsRoute: typeof PublicReviewsRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicArticlesIdRoute: typeof PublicArticlesIdRoute
  PublicPackagesIdRoute: typeof PublicPackagesIdRoute
  PublicToolsFitnessCalculatorRoute: typeof PublicToolsFitnessCalculatorRoute
  PublicTrainersIdRoute: typeof PublicTrainersIdRoute
  PublicArticlesIndexRoute: typeof PublicArticlesIndexRoute
  PublicPackagesIndexRoute: typeof PublicPackagesIndexRoute
  PublicTrainersIndexRoute: typeof PublicTrainersIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicForgotPasswordRoute: PublicForgotPasswordRoute,
  PublicGymInfoRoute: PublicGymInfoRoute,
  PublicLoginRoute: PublicLoginRoute,
  PublicRegisterRoute: PublicRegisterRoute,
  PublicRegisterTrainerRoute: PublicRegisterTrainerRoute,
  PublicReviewsRoute: PublicReviewsRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicArticlesIdRoute: PublicArticlesIdRoute,
  PublicPackagesIdRoute: PublicPackagesIdRoute,
  PublicToolsFitnessCalculatorRoute: PublicToolsFitnessCalculatorRoute,
  PublicTrainersIdRoute: PublicTrainersIdRoute,
  PublicArticlesIndexRoute: PublicArticlesIndexRoute,
  PublicPackagesIndexRoute: PublicPackagesIndexRoute,
  PublicTrainersIndexRoute: PublicTrainersIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AdminRouteChildren {
  AdminBranchesRoute: typeof AdminBranchesRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBranchesRoute: AdminBranchesRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CustomerRouteChildren {
  CustomerAssessmentRoute: typeof CustomerAssessmentRoute
  CustomerAvailabilityRoute: typeof CustomerAvailabilityRoute
  CustomerBookPtRoute: typeof CustomerBookPtRoute
  CustomerChangePasswordRoute: typeof CustomerChangePasswordRoute
  CustomerCheckInRoute: typeof CustomerCheckInRoute
  CustomerCheckInScreenRoute: typeof CustomerCheckInScreenRoute
  CustomerMetricsRoute: typeof CustomerMetricsRoute
  CustomerPackagesRoute: typeof CustomerPackagesRoute
  CustomerProfileRoute: typeof CustomerProfileRoute
  CustomerPurchaseRoute: typeof CustomerPurchaseRoute
  CustomerRefundRoute: typeof CustomerRefundRoute
  CustomerRescheduleRoute: typeof CustomerRescheduleRoute
  CustomerReviewRoute: typeof CustomerReviewRoute
  CustomerScheduleRoute: typeof CustomerScheduleRoute
  CustomerIndexRoute: typeof CustomerIndexRoute
  CustomerSessionsIdRoute: typeof CustomerSessionsIdRoute
  CustomerSessionsIndexRoute: typeof CustomerSessionsIndexRoute
}

const CustomerRouteChildren: CustomerRouteChildren = {
  CustomerAssessmentRoute: CustomerAssessmentRoute,
  CustomerAvailabilityRoute: CustomerAvailabilityRoute,
  CustomerBookPtRoute: CustomerBookPtRoute,
  CustomerChangePasswordRoute: CustomerChangePasswordRoute,
  CustomerCheckInRoute: CustomerCheckInRoute,
  CustomerCheckInScreenRoute: CustomerCheckInScreenRoute,
  CustomerMetricsRoute: CustomerMetricsRoute,
  CustomerPackagesRoute: CustomerPackagesRoute,
  CustomerProfileRoute: CustomerProfileRoute,
  CustomerPurchaseRoute: CustomerPurchaseRoute,
  CustomerRefundRoute: CustomerRefundRoute,
  CustomerRescheduleRoute: CustomerRescheduleRoute,
  CustomerReviewRoute: CustomerReviewRoute,
  CustomerScheduleRoute: CustomerScheduleRoute,
  CustomerIndexRoute: CustomerIndexRoute,
  CustomerSessionsIdRoute: CustomerSessionsIdRoute,
  CustomerSessionsIndexRoute: CustomerSessionsIndexRoute,
}

const CustomerRouteWithChildren = CustomerRoute._addFileChildren(
  CustomerRouteChildren,
)

interface ManagerRouteChildren {
  ManagerMembershipsRoute: typeof ManagerMembershipsRoute
  ManagerReportsRoute: typeof ManagerReportsRoute
  ManagerStaffRoute: typeof ManagerStaffRoute
  ManagerIndexRoute: typeof ManagerIndexRoute
}

const ManagerRouteChildren: ManagerRouteChildren = {
  ManagerMembershipsRoute: ManagerMembershipsRoute,
  ManagerReportsRoute: ManagerReportsRoute,
  ManagerStaffRoute: ManagerStaffRoute,
  ManagerIndexRoute: ManagerIndexRoute,
}

const ManagerRouteWithChildren =
  ManagerRoute._addFileChildren(ManagerRouteChildren)

interface StaffRouteChildren {
  StaffCheckInRoute: typeof StaffCheckInRoute
  StaffClassesRoute: typeof StaffClassesRoute
  StaffMembersRoute: typeof StaffMembersRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffCheckInRoute: StaffCheckInRoute,
  StaffClassesRoute: StaffClassesRoute,
  StaffMembersRoute: StaffMembersRoute,
  StaffIndexRoute: StaffIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

interface TrainerRouteChildren {
  TrainerClientsRoute: typeof TrainerClientsRoute
  TrainerProgramsRoute: typeof TrainerProgramsRoute
  TrainerScheduleRoute: typeof TrainerScheduleRoute
  TrainerIndexRoute: typeof TrainerIndexRoute
}

const TrainerRouteChildren: TrainerRouteChildren = {
  TrainerClientsRoute: TrainerClientsRoute,
  TrainerProgramsRoute: TrainerProgramsRoute,
  TrainerScheduleRoute: TrainerScheduleRoute,
  TrainerIndexRoute: TrainerIndexRoute,
}

const TrainerRouteWithChildren =
  TrainerRoute._addFileChildren(TrainerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  CustomerRoute: CustomerRouteWithChildren,
  GuestRoute: GuestRoute,
  HubRoute: HubRoute,
  ManagerRoute: ManagerRouteWithChildren,
  StaffRoute: StaffRouteWithChildren,
  TrainerRoute: TrainerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
